# Generated by Django 3.2.5 on 2021-07-05 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pitch_decks', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deckimage',
            old_name='title1',
            new_name='title',
        ),
    ]
