# Generated by Django 3.2.5 on 2021-07-19 08:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pitch_decks', '0003_auto_20210718_2348'),
    ]

    operations = [
        migrations.AddField(
            model_name='pitchdeck',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
    ]
